// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.defascat.roo.realworld.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.defascat.roo.realworld.domain.Version;
import org.defascat.roo.realworld.domain.VersionDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect VersionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VersionDataOnDemand: @Component;
    
    private Random VersionDataOnDemand.rnd = new SecureRandom();
    
    private List<Version> VersionDataOnDemand.data;
    
    public Version VersionDataOnDemand.getNewTransientVersion(int index) {
        Version obj = new Version();
        setName(obj, index);
        return obj;
    }
    
    public void VersionDataOnDemand.setName(Version obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Version VersionDataOnDemand.getSpecificVersion(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Version obj = data.get(index);
        Long id = obj.getId();
        return Version.findVersion(id);
    }
    
    public Version VersionDataOnDemand.getRandomVersion() {
        init();
        Version obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Version.findVersion(id);
    }
    
    public boolean VersionDataOnDemand.modifyVersion(Version obj) {
        return false;
    }
    
    public void VersionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Version.findVersionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Version' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Version>();
        for (int i = 0; i < 10; i++) {
            Version obj = getNewTransientVersion(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
