// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.defascat.roo.realworld.domain;

import org.defascat.roo.realworld.domain.Server;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Server_Roo_Configurable {
    
    declare @type: Server: @Configurable;
    
}
